//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaHocTap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_QuanLyKetQuaHocTapEntities : DbContext
    {
        public db_QuanLyKetQuaHocTapEntities()
            : base("name=db_QuanLyKetQuaHocTapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
<<<<<<< HEAD
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_ChiTietDGRL> tb_ChiTietDGRL { get; set; }
        public virtual DbSet<tb_ChiTietTieuChiDGRL> tb_ChiTietTieuChiDGRL { get; set; }
        public virtual DbSet<tb_DanhGiaRenLuyen> tb_DanhGiaRenLuyen { get; set; }
        public virtual DbSet<tb_DiemHocPhan> tb_DiemHocPhan { get; set; }
        public virtual DbSet<tb_KhoaVien> tb_KhoaVien { get; set; }
        public virtual DbSet<tb_MinhChungDGRL> tb_MinhChungDGRL { get; set; }
        public virtual DbSet<tb_NoiDungDGRL> tb_NoiDungDGRL { get; set; }
        public virtual DbSet<tb_Nganh> tb_Nganh { get; set; }
        public virtual DbSet<tb_PhongHoc> tb_PhongHoc { get; set; }
        public virtual DbSet<tb_QuanTri> tb_QuanTri { get; set; }
        public virtual DbSet<tb_TaiKhoan> tb_TaiKhoan { get; set; }
        public virtual DbSet<tb_TieuChiDGRL> tb_TieuChiDGRL { get; set; }
        public virtual DbSet<tb_ThongTinBuoiHoc> tb_ThongTinBuoiHoc { get; set; }
        public virtual DbSet<tb_CoVanHocTap> tb_CoVanHocTap { get; set; }
        public virtual DbSet<tb_CTGD> tb_CTGD { get; set; }
        public virtual DbSet<tb_MonHoc> tb_MonHoc { get; set; }
        public virtual DbSet<tb_GiangVien> tb_GiangVien { get; set; }
        public virtual DbSet<tb_SinhVien> tb_SinhVien { get; set; }
        public virtual DbSet<tb_HocPhan> tb_HocPhan { get; set; }
=======
        public virtual DbSet<tb_ChiTietDGRL> tb_ChiTietDGRL { get; set; }
        public virtual DbSet<tb_ChiTietTieuChiDGRL> tb_ChiTietTieuChiDGRL { get; set; }
        public virtual DbSet<tb_CoVanHocTap> tb_CoVanHocTap { get; set; }
        public virtual DbSet<tb_CTGD> tb_CTGD { get; set; }
        public virtual DbSet<tb_DanhGiaRenLuyen> tb_DanhGiaRenLuyen { get; set; }
        public virtual DbSet<tb_DiemHocPhan> tb_DiemHocPhan { get; set; }
        public virtual DbSet<tb_GiangVien> tb_GiangVien { get; set; }
        public virtual DbSet<tb_HocPhan> tb_HocPhan { get; set; }
        public virtual DbSet<tb_KhoaVien> tb_KhoaVien { get; set; }
        public virtual DbSet<tb_MinhChungDGRL> tb_MinhChungDGRL { get; set; }
        public virtual DbSet<tb_MonHoc> tb_MonHoc { get; set; }
        public virtual DbSet<tb_Nganh> tb_Nganh { get; set; }
        public virtual DbSet<tb_NoiDungDGRL> tb_NoiDungDGRL { get; set; }
        public virtual DbSet<tb_PhongHoc> tb_PhongHoc { get; set; }
        public virtual DbSet<tb_QuanTri> tb_QuanTri { get; set; }
        public virtual DbSet<tb_SinhVien> tb_SinhVien { get; set; }
        public virtual DbSet<tb_TaiKhoan> tb_TaiKhoan { get; set; }
        public virtual DbSet<tb_ThongTinBuoiHoc> tb_ThongTinBuoiHoc { get; set; }
        public virtual DbSet<tb_TieuChiDGRL> tb_TieuChiDGRL { get; set; }
>>>>>>> f917e0184172b7d7be1a550e72214e58d3e1608b
    }
}
