//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChiTietDGRL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ChiTietDGRL()
        {
            this.tb_MinhChungDGRL = new HashSet<tb_MinhChungDGRL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_DanhGiaRenLuyen { get; set; }
        public Nullable<int> ID_ChiTietTieuChiDGRL { get; set; }
        public Nullable<int> DiemTuDG { get; set; }
        public Nullable<int> DiemCVHT { get; set; }
        public Nullable<int> DiemKhoa { get; set; }
    
        public virtual tb_ChiTietTieuChiDGRL tb_ChiTietTieuChiDGRL { get; set; }
        public virtual tb_DanhGiaRenLuyen tb_DanhGiaRenLuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MinhChungDGRL> tb_MinhChungDGRL { get; set; }
    }
}
