//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChiTietTieuChiDGRL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ChiTietTieuChiDGRL()
        {
            this.tb_ChiTietDGRL = new HashSet<tb_ChiTietDGRL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_TieuChiDGRL { get; set; }
        public Nullable<int> STT { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> DiemToiThieu { get; set; }
        public Nullable<int> DiemToiDa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietDGRL> tb_ChiTietDGRL { get; set; }
        public virtual tb_TieuChiDGRL tb_TieuChiDGRL { get; set; }
    }
}
