//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DanhGiaRenLuyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DanhGiaRenLuyen()
        {
            this.tb_ChiTietDGRL = new HashSet<tb_ChiTietDGRL>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_NoiDungDGRL { get; set; }
        public Nullable<int> ID_SinhVien { get; set; }
        public Nullable<int> DiemTongTuDG { get; set; }
        public Nullable<int> DiemTongCVDG { get; set; }
        public Nullable<int> DiemTongKhoaDG { get; set; }
        public Nullable<int> HocKi { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietDGRL> tb_ChiTietDGRL { get; set; }
        public virtual tb_NoiDungDGRL tb_NoiDungDGRL { get; set; }
        public virtual tb_SinhVien tb_SinhVien { get; set; }
    }
}
