//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DangKyMon
    {
        public int ID { get; set; }
        public Nullable<int> ID_KhoaHoc { get; set; }
        public Nullable<int> ID_SinhVien { get; set; }
        public Nullable<int> NamHoc_DK { get; set; }
        public Nullable<int> HocKi_DK { get; set; }
        public Nullable<double> Diem_KTGK { get; set; }
        public Nullable<double> Diem_KTCK { get; set; }
        public string XepLoai { get; set; }
    
        public virtual tb_KhoaHoc tb_KhoaHoc { get; set; }
        public virtual tb_SinhVien tb_SinhVien { get; set; }
    }
}
