//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DiemHocPhan
    {
        public int ID { get; set; }
        public Nullable<int> ID_HocPhan { get; set; }
        public Nullable<int> ID_SinhVien { get; set; }
        public Nullable<int> NamHoc_DK { get; set; }
        public Nullable<int> HocKi_DK { get; set; }
        public Nullable<double> DiemGK { get; set; }
        public Nullable<double> DiemCK { get; set; }
    
        public virtual tb_HocPhan tb_HocPhan { get; set; }
        public virtual tb_SinhVien tb_SinhVien { get; set; }
    }
}
