//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_HocPhan()
        {
            this.tb_DiemHocPhan = new HashSet<tb_DiemHocPhan>();
            this.tb_ThongTinBuoiHoc = new HashSet<tb_ThongTinBuoiHoc>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_GiangVien { get; set; }
        public Nullable<int> ID_MonHoc { get; set; }
        public string MaHP { get; set; }
        public Nullable<int> SiSo_HienTai { get; set; }
        public Nullable<int> SiSo_ToiDa { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayKhoiTao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DiemHocPhan> tb_DiemHocPhan { get; set; }
        public virtual tb_GiangVien tb_GiangVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ThongTinBuoiHoc> tb_ThongTinBuoiHoc { get; set; }
        public virtual tb_MonHoc tb_MonHoc { get; set; }
    }
}
