//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MonHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_MonHoc()
        {
            this.tb_HocPhan = new HashSet<tb_HocPhan>();
            this.tb_GiangVien = new HashSet<tb_GiangVien>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Nganh { get; set; }
        public Nullable<int> ID_CTGD { get; set; }
        public string MaMH { get; set; }
        public string TenMH { get; set; }
        public Nullable<int> SoTC { get; set; }
        public Nullable<bool> BatBuoc { get; set; }
        public Nullable<int> SoTietLT { get; set; }
        public Nullable<int> SoTietTH { get; set; }
        public Nullable<bool> XetDiem { get; set; }
        public Nullable<int> TrongSoGiuaKi { get; set; }
        public Nullable<int> LoaiMonHoc { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> HocKi { get; set; }
    
        public virtual tb_CTGD tb_CTGD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_HocPhan> tb_HocPhan { get; set; }
        public virtual tb_Nganh tb_Nganh { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_GiangVien> tb_GiangVien { get; set; }
    }
}
