//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_MinhChungDGRL
    {
        public int ID { get; set; }
        public Nullable<int> ID_ChiTietDGRL { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> STT { get; set; }
    
        public virtual tb_ChiTietDGRL tb_ChiTietDGRL { get; set; }
    }
}
