//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Nganh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Nganh()
        {
            this.tb_SinhVien = new HashSet<tb_SinhVien>();
            this.tb_CoVanHocTap = new HashSet<tb_CoVanHocTap>();
            this.tb_MonHoc = new HashSet<tb_MonHoc>();
        }
    
        public int ID { get; set; }
        public string MaNganh { get; set; }
        public string TenNganh { get; set; }
        public Nullable<int> ID_KhoaVien { get; set; }
        public Nullable<int> SoNam { get; set; }
    
        public virtual tb_KhoaVien tb_KhoaVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SinhVien> tb_SinhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CoVanHocTap> tb_CoVanHocTap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_MonHoc> tb_MonHoc { get; set; }
    }
}
