//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKetQuaHocTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ThongTinBuoiHoc
    {
        public int ID { get; set; }
        public Nullable<int> ID_HocPhan { get; set; }
        public Nullable<int> MaPH { get; set; }
        public Nullable<System.DateTime> NgayHoc { get; set; }
        public Nullable<int> TietBatDau { get; set; }
        public Nullable<int> TietKetThuc { get; set; }
        public Nullable<int> SoTiet { get; set; }
    
        public virtual tb_HocPhan tb_HocPhan { get; set; }
        public virtual tb_PhongHoc tb_PhongHoc { get; set; }
    }
}
